{% set name = "streamz_ext" %}
{% set version = "0.1.0" %}
{% set sha256 = "110256c72aefb9229315d433dc4dd5599ee85486ff416f87433dc3da1042c549" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed . 

requirements:
  build:
    - python
    - pip
  run:
    - python
    - toolz
    - tornado
    - streamz
    - distributed


test:
  imports:
    - streamz
    - streamz.core
    - streamz.dask

about:
  home: https://github.com/xpdAcq/streamz_ext
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Extension of Streamz'
  dev_url: https://github.com/xpdAcq/streamz_ext

extra:
  recipe-maintainers:
    - CJ-Wright
