travis:
  secure:
    BINSTAR_TOKEN: ZVhUHLTi063l0Znt+li2Ii+KMJtJ4L8xSre5GLqKNwJB/KRkyG8H0nzBS/2pSVSAWQrGEIK+9ghxfWZIdmjNe3YSWMGpbV16CyrE83Q/nYEJ5YOIdMjRqR1beHdASfnizc7qRSL7HF4xC87O+RpOBJN2CohfmMMkLD3uSh10xLnu76mzLRpMQ9egEmUqH4qF5+Y/Ij6mh1PnE3qkPwhY7udOODusX7bfTJzdAeUpDRBZJ8R5piAZzQzJV0k5PesGUHLyK+2HHiW1+vHNEOxNGq8sgBM1AvAdXMvXpqV6JgurgpepkQnn/KFXjvEplszbTKL+HvdYztD+fEylB5XS3CPEt49IjZFDrfY/FnhFyJW0MPXYBQw0mHhwCiawLBP3nNnKL90AknTAbYCw1ORni9Bqan7fmM3jRuOsU3FanOsZEX7mx6PSgiql3AWKSPPnn3/GrHlCwU3xhiY+x3FfzPpDwJ3HPQJylZKwyTsNYcjj9uysELO9J0yoRJ0CNfytpOHhxxrBEuyrFLgfWp9aOccWLWUmT3dvQf8uD3Nt1+V2dLcK1qRe9Kej8IG6liuyhxj6OABFH5iwFRbDGjOmjT9S44wSaL6x9Q4HDNrvn22FLSo/RzGGqYxrgVRkmJAH96q6QpeOKw2O6/Mmw7ZpfqZnw+fcMd19i4TXVHAJ3rE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
